# Generated by Django 3.0.8 on 2021-09-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='ref',
            field=models.CharField(default='', max_length=100),
        ),
    ]
